<p>
  <img title="Broken File" class="broken" src="../resources/images/broken.gif" width="20" height="22"> Hello!

  I am Gavin "ioi_xd" Parker, a 20 year old programmer<noprint> (see the windows beside this for more info on that)
  </noprint>, artist, and aspiring filmmaker.
</p>

<p>I specialize in writing applications in Rust, Go, and Python. I also can write an HTML/CSS/JS frontend and have written backends in Javascript and PHP. I decided not to make programming my job because I would prefer to do it as a hobby, realizing that the industry values getting products out as fast as possible over good programming, and have instead decided to persue IT.</p>

<p>As a freelance programmer, I have:
<ul>
	<li>Created my own game engine, intended to be used with friends. It's meant to be used via Lua and a considerably large amount of code is in place to bind a Rust physics library to it. (https://github.com/IoIxD/engine_xd/)</li>
	<li>Created a Minecraft plugin that allows me to make other plugins without Java and make them with Rust instead. It was accomplished via a Python script that takes data generated by a Java program to create 4,492,129 lines of code. (https://github.com/orgs/BlackBoxMC/repositories)</li>
	<li>Created a website via the Golang programming language that makes forums within the chat software “Discord” appear on a real website, allowing them to be found on Google (https://github.com/IoIxD/dforum)</li>
	<li>Created another custom forum software, also via Golang, for a website between me and friends (https://github.com/AwesomewareInc/LaffForum)</li>
	<li>Created two programs, one in Golang and the other in Rust, that generate psychedlic imagery by combining two gradient/noise images in a special way (https://github.com/IoIxD/glitchfk).</li>
	<li>Created a Golang (and later Rust) program that turns PNGs into SVGs on a pixel by pixel basis, allowing me to display retro pixel art on websites without scaling issues (https://github.com/IoIxD/png_to_svg)</li>
	<li>Created a website via HTML/CSS/JavaScript that allows you to recolor the VLC logo (a traffic cone) to represent a LGBTQIA+ pride flag (https://github.com/IoIxD/VLCConeChanger)</li>
    	<li style='margin-left: 1em'>Created a website via Golang that displays archives from several D&D servers that me and friends have been in (https://github.com/AwesomewareInc/DungeonArchive). Also created a script via Python that backs up said servers (https://github.com/AwesomewareInc/PyDiscordArchiver)</li>
	<li style='margin-left: 1em'>Created various Minecraft plugins within Java, including:</li>
    	<li style='margin-left: 1em'>One that allows you to view a Mastodon server in game (https://github.com/AwesomewareInc/Mastodwarf)</li>
    	<li style='margin-left: 1em'>One that adds Pokemon cards into the game (https://github.com/AwesomewareInc/PokemonCardPlugin)</li>
    	<li style='margin-left: 1em'>One that allows you to throw the TNT and Anvil blocks at players (https://github.com/AwesomewareInc/Hookshot)</li>
</ul>
</p>

<p style='color: red'>You can move, close, minimize, and maximize the windows on this website! Try it!</p>

<p>
  <noprint>
    <center>
      <b>hey check these sites out:</b><br>
	<a target="_blank" href="https://modarchive.org/"><img alt="modarchive.org" src="https://content.pouet.net/buttons/tma_c.gif" border="0"></a>
	<a target="_blank" href="https://web.archive.org/web/19961229152939im_/http://www.windows95.com/"><img src="https://web.archive.org/web/19961229152939im_/http://www2.windows95.com/gifs/w95com.gif" border="0"></a>
	<a target="_blank" href="https://projectlounge.pw"><img src="https://essem.space/images/projectloungenow.gif"></a>
	<a href="https://epicblazed.com" target="_blank"><img src="https://boxy.neocities.org/images/EpicBlazedButton.png" alt="Epic Blazed"></a>
	<a href="https://ioletsgo.gay" target="_blank"><img src="https://ioletsgo.gay/Assets/buttons/ivorybutton.gif"></a> 
	<a href="https://squibbus.neocities.org/"><img src="https://ioletsgo.gay/Assets/buttons/axelbutton.gif"></a> 
	<a href="https://nicox.neocities.org/"><img src="https://ioletsgo.gay/Assets/buttons/nicox.png"></a> 
	<a href="https://danielah05.github.io/"><img src="https://ioletsgo.gay/Assets/buttons/daniela.gif"></a> 
	<a href="https://c7.pm/"><img src="https://ioletsgo.gay/Assets/buttons/c7-badge.png"></a> 
	<a href="https://radixcomet.neocities.org/"><img src="https://ioletsgo.gay/Assets/buttons/radixbutton.png"></a>
	<a href="https://nixgoat.me/"><img src="https://ioletsgo.gay/Assets/buttons/nixgoatbutton.gif"></a>
	<a href="https://invoxiplaygames.uk/"><img src="https://ioletsgo.gay/Assets/buttons/ipg.png"></a>
	<a href="https://thxdee.neocities.org/"><img src="https://ioletsgo.gay/Assets/buttons/thxdee.gif"></a>
    </center>
  </noprint>
</p>
